services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
  app:
    build:
      context: ./backend/User
    ports:
      - "8000:8000"
    volumes:
      - ./backend/User:/app
    command: >
      sh -c " python manage.py db_readiness &&
              python manage.py migrate &&
              python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=db-localdev
      - DB_USER=localdevuser
      - DB_PASS=localdevpassword
    depends_on:
      - db
  llama-designer-server:
    build:
      context: ./backend/llama3-designer
    container_name: llama-designer
    depends_on:
      - rabbitmq
    ports:
      - "5000:5000"
    volumes:
      - ./backend/llama3-designer:/app # Mount your code directory into /app
    # Ensure model is visible
    environment:
      - FLASK_APP=app.py
      - OMP_NUM_THREADS=1
      - NUMEXPR_NUM_THREADS=1
      - MKL_NUM_THREADS=1
      - FLASK_ENV=development # Enables auto-reload
    command: python app.py

  langchain-service:
    build:
      context: ./backend/langchain
    container_name: langchain-app
    ports:
      - "8001:8001"
    volumes:
      - ./backend/langchain:/app
    environment:
      - FLASK_APP=main.py
    command: python main.py

  ue2net_service:
    build: ./backend/U2net/U-2-Net
    environment:
      - RABBITMQ_HOST=rabbitmq
    ports:
      - "5002:5002" # Flask port
    volumes:
      - ./backend/U2net/U-2-Net:/app

  db:
    image: postgres:14-alpine
    volumes:
      - db-localdev-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=db-localdev
      - POSTGRES_USER=localdevuser
      - POSTGRES_PASSWORD=localdevpassword
  qdrant:
    image: qdrant/qdrant:latest
    volumes:
      - qdrant-data:/qdrant/storage
    ports:
      - "6333:6333"
      - "6334:6334"
    environment:
      - QDRANT__STORAGE__STORAGE_PATH=/qdrant/storage

  mongo:
    image: mongo:6.0
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongouser
      - MONGO_INITDB_ROOT_PASSWORD=mongopassword

volumes:
  db-localdev-data:
  qdrant-data:
  mongo-data:
