services:
  app:
    build:
      context: ./backend/User
    ports:
      - "8000:8000"
    volumes:
      - ./backend/User:/app
    command: >
      sh -c " python manage.py db_readiness &&
              python manage.py migrate &&
              python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=db-localdev
      - DB_USER=localdevuser
      - DB_PASS=localdevpassword
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    volumes:
      - db-localdev-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=db-localdev
      - POSTGRES_USER=localdevuser
      - POSTGRES_PASSWORD=localdevpassword
  qdrant:
    image: qdrant/qdrant:latest
    volumes:
      - qdrant-data:/qdrant/storage
    ports:
      - "6333:6333"
      - "6334:6334"
    environment:
      - QDRANT__STORAGE__STORAGE_PATH=/qdrant/storage

  mongo:
    image: mongo:6.0
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongouser
      - MONGO_INITDB_ROOT_PASSWORD=mongopassword

volumes:
  db-localdev-data:
  qdrant-data:
  mongo-data:
