# Use NVIDIA CUDA base image
FROM nvidia/cuda:12.3.1-devel-ubuntu22.04

ENV DEBIAN_FRONTEND=noninteractive
ARG PIP_CACHE_DIR=/tmp/pip_cache
# Install dependencies (now without hanging on tzdata)
RUN apt-get update && apt-get install -y \
        python3-dev python3-pip \
        curl \
        build-essential \
        software-properties-common \
        ninja-build \  
        git \     
    && rm -rf /var/lib/apt/lists/*

RUN pip install llama-cpp-python \
    --no-cache-dir \
    --extra-index-url https://abetlen.github.io/llama-cpp-python/whl/cu123
# Set working directory
WORKDIR /app

# # Copy requirements and install dependencies
COPY requirements.txt .
RUN --mount=type=cache,target=${PIP_CACHE_DIR} \
    pip install --no-cache-dir --default-timeout=100 -r requirements.txt

# Install llama-cpp-python with CUDA support
# Use the pre-built wheel if possible, or build with CUDA support
# ARG CMAKE_ARGS="-DLLAMA_CUBLAS=on"
# ARG FORCE_CMAKE=1
# RUN pip install --no-cache-dir llama-cpp-python --no-binary llama-cpp-python

# Copy the application code
COPY . .

# Expose port
EXPOSE 5000

# Run the Flask app
CMD ["python3", "app.py"]